### ISSUE TITLE
Update default Dokka version to 1.9.10

### ISSUE THREAD

**Issue by jbartok** [adamko-dev/dokkatoo#137]
Reason for the request: https://github.com/gradle/gradle/issues/26479

**Comment by aSemy** [comment]
Hi @jbartok, thanks for the request.

I'll make a release soon, but feel free to update your build script to use Dokka 1.9.10

```kotlin
// build.gradle.kts

plugins {
  id("dev.adamko.dokkatoo-html")
}

dokkatoo {
  versions {
    jetbrainsDokka.set("1.9.10")
  }
}
```

As far as I'm aware there haven't been any changes to the Dokka configuration classes in a long time, so Dokkatoo should support most Dokka versions. If there are any problems, then let me know!

**Comment by jbartok** [comment]
Thanks @aSemy, the workaround you suggested works nicely.
