### ISSUE TITLE
Aggregating modules doesn't work without manually adding a dependency on `all-modules-page-plugin`

### ISSUE THREAD

**Issue by aSemy** [adamko-dev/dokkatoo#14]
Currently in order to create a Dokka publication that aggregates subprojects, it's required to manually add a dependency on `all-modules-page-plugin`

```kotlin
plugins {
  kotlin("jvm") version "1.7.20" apply false
  id("dev.adamko.dokkatoo") version "0.0.2-SNAPSHOT"
}

dependencies {
  dokkatoo(project(":parentProject:childProjectA"))
  dokkatoo(project(":parentProject:childProjectB"))

  // A dependency on all-modules-page-plugin is required for aggregating subprojects.
  // A version is not required, Dokkatoo will automatically add one.
  dokkatooPluginHtml("org.jetbrains.dokka:all-modules-page-plugin")
}
```

This dependency should be added automatically.

**Comment by hfhbd** [comment]
Does this issue also include the adding all modules manually using `dependencies { dokkatoo(projects.foo) }`? With big projects and adding new modules it is easy to forget to add the new module in the root project too. Would using a BuildService help to register the projects automatically?

**Comment by aSemy** [comment]
@hfhbd So you want Dokkatoo to automatically set up a multi-module aggregation, if possible? I think that's worth investigating, so please make a new issue. I think it would be possible for Dokkatoot to implement that using [default dependencies](https://docs.gradle.org/8.1.1/userguide/implementing_gradle_plugins.html#providing_default_dependencies_for_plugins). Such a feature would be dependent on fixing this issue.

**Comment by aSemy** [comment]
I've pushed a change #127 that makes adding the dependency slightly easier and less verbose. Dokkatoo will now automatically add a version, so all that's required is:

```kotlin
dependencies {
  dokkatoo(project(":parentProject:childProjectA"))
  dokkatoo(project(":parentProject:childProjectB"))

  // A dependency on all-modules-page-plugin is required at the moment.
  // A version is not required, Dokkatoo will automatically add one.
  dokkatooPluginHtml("org.jetbrains.dokka:all-modules-page-plugin")
}
```

The version will be set from the version set in the Dokkatoo extension:

```kotlin
// build.gradle.kts

dokkatoo {
  versions {
    jetbrainsDokka.set("1.9.10")
  }
}
```
