### ISSUE TITLE
Dokka plugin support

### ISSUE THREAD

**Issue by hfhbd** [adamko-dev/dokkatoo#186]
Can you please add a sample how to use a Dokka plugin, like the mermaid plugin? 
https://github.com/glureau/dokka-mermaid

With dokka, all you need is to add it to the top level project:
```kotlin
dependencies {
  dokkaPlugin("com.glureau:html-mermaid-dokka-plugin:0.6.0")
}
```

**Comment by aSemy** [comment]
More examples would definitely help.

Does adding it like this work?

```kotlin
dependencies {
  dokkatooPluginHtml("com.glureau:html-mermaid-dokka-plugin:0.6.0")
}
```

Related: 

* https://github.com/adamko-dev/dokkatoo/discussions/175
* https://github.com/adamko-dev/dokkatoo/issues/121

**Comment by hfhbd** [comment]
Yes, it does work, thanks!

**Comment by aSemy** [comment]
New plan: add a `dokkatooPlugin` Configuration that the `dokkatooPlugin$Format` Configurations will extend from.

This will simplify adding plugins.

**Comment by aSemy** [comment]
I've updated the docs, and there's now a page for the Dokka Engine Plugins

https://adamko-dev.github.io/dokkatoo/docs/configuring/dokka-engine-plugins
