### ISSUE TITLE
KMP: Support for removing test sources from the output

### ISSUE THREAD

**Issue by EdricChan03** [adamko-dev/dokkatoo#51]
Seems that the test sources are included by default - not sure if Dokka hid it by default, but it would be nice to have an option of excluding test sources from the resulting Dokka output.

Currently, a workaround would be to remove `*Test` sources by setting `suppress` to `true`

**Comment by aSemy** [comment]
Thanks for the report, I'll look into it after the Kotlin Multiplatform refactoring being done for #50. I suspect that will also fix this issue.

While the test source sets will be included in the generated `dokka_parameters.json` files, they should be excluded when they are actually sent to the Dokka generator:

https://github.com/adamko-dev/dokkatoo/blob/9eadee7c06ed9b1d4c80f34bd709de61e19e1834/modules/dokkatoo-plugin/src/main/kotlin/tasks/DokkatooPrepareParametersTask.kt#L146-L150

I don't think `suppressed` is encoded to the `dokka_parameters.json` file, so maybe it's not being respected across subprojects.

**Comment by EdricChan03** [comment]
Test sources also seem to be excluded now as per #50, so I guess this can be closed as well
