### ISSUE TITLE
Failed to download package-list from https://package-list

### ISSUE THREAD

**Issue by hfhbd** [adamko-dev/dokkatoo#84]
This error message is somehow misleading, because it does not contain any url or the name of the registered Link domain-object.

`Failed to download package-list from https://package-list, this might suggest that remote resource is not available, module is empty or dokka output got corrupted`

I used Dokkatoo 1.3.0 and Gradle 8.1.1.
I will create a reproducer later, but this is only possible by removing each url entry and trial and error.

**Comment by aSemy** [comment]
This error originates from Dokka, but maybe Dokkatoo can do something to round off the rough edges.

**Comment by hfhbd** [comment]
I created a reproducer. It is only reproducible with dokkatoo and only with root level urls, like api.ktor.io or my domain uuid.softwork.app Both urls contain the package-list. So I guess, there is a bug in your mapping.
[a.zip](https://github.com/adamko-dev/dokkatoo/files/11626748/a.zip)

**Comment by aSemy** [comment]
Ahh nice find! I'll try and fix it. Ideally Dokka should be updated to be more clever too, and automatically build the URL - would you mind making an issue on the Dokka repo?

**Comment by aSemy** [comment]
Yes that's right, both should be supported. A naïve solution would be to use some string manipulation to split/join with the correct slash separators, but possibly there's some URI builder that can be used which will be more robust.
